name: Publish package
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Check out dependencies
      uses: actions/checkout@v4
      with:
        repository: rks/file_exchange_toolbox
        path: mpm_repository/file_exchange_toolbox
        token: ${{ secrets.TOGGLE_LIGHTS_PUBLISH_PACKAGE }}
        sparse-checkout: .

    - name: Check out repository
      uses: actions/checkout@v4
      with:
        path: ${{ github.repository.name }}

    - name: Verify checkout
      run: |
        ls -lA .
