name: Publish package
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Check out repository
      uses: actions/checkout@v4
      with:
        path: src
    - name: Verify repository checkout
      run: |
        pwd; ls -lA .
    - name: Check out dependencies
      uses: actions/checkout@v4
      with:
        repository: rks/file_exchange_toolbox
        path: mpm_repository/file_exchange_toolbox
        token: ${{ secrets.TOGGLE_LIGHTS_PUBLISH_PACKAGE }}
    - name: Verify dependency checkout
      run: |
        pwd; ls -lA .
