name: Publish package
on:
  workflow_dispatch:

env:
  MPM_REPOSITORY_PATH: ${{ github.workspace }}/build/mpm_repository

jobs:
  setup:
    runs-on: ubuntu-22.04
    steps:
    - name: Check out repository
      uses: actions/checkout@v4
    - name: Check out dependencies
      uses: actions/checkout@v4
      with:
        repository: rks/file_exchange_toolbox
        path: ${{ env.MPM_REPOSITORY_PATH }}
        token: ${{ secrets.TOGGLE_LIGHTS_PUBLISH_PACKAGE }}
    - name: Verify dependency checkout
      run: |
        pwd; ls -lA .
    - name: Set up MATLAB
      uses: matlab-actions/setup-matlab@v2
      with:
        release: latest-including-prerelease
    - name: Run build
      uses: matlab-actions/run-build@v2
      with:
        tasks: package
